[package]
name = "cnn_gap_contract"
version = "0.1.0"
type = "contract"
authors = ["wei3erHase"]
license = "MIT"
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git = "https://github.com/defi-wonderland/aztec-nr", tag = "v4.3.0-test.0", directory = "aztec" }
zkml = { path = "../zkml" }
