name: PR Checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    uses: defi-wonderland/aztec-ci-actions/.github/workflows/run-tests.yml@v0
    secrets: inherit

  e2e:
    uses: ./.github/workflows/run-e2e.yml
    secrets: inherit

  benchmark:
    uses: defi-wonderland/aztec-benchmark/.github/workflows/pr-benchmark.yml@4.0.0-devnet.2-patch.1
    permissions:
      contents: read
      pull-requests: write
      issues: write
      actions: read
    secrets: inherit
